### ISSUE TITLE
how too encrypt long text with rsa public key in version 0.4.0

### ISSUE THREAD

**Issue by cjon123** [RustCrypto/RSA#100]
i want to encrypt long text with RSAPublicKey , but it exception that message too long . then encrypt in batches with RSAPublicKey , but an error is reported description when decrypting . is there any good way please?

**Comment by tarcieri** [comment]
The best way to do that is some sort of hybrid cryptosystem leveraging something like RSA-KEM to encapsulate a key for a symmetric cipher like AES-GCM or ChaCha20Poly1305.

I’m not sure if there’s an off-the-shelf scheme for that in Rust, though.

If you have trouble finding one and don’t specifically require RSA but just general-purpose public key cryptography, there are several schemes that use elliptic curves.

**Comment by cjon123** [comment]
> The best way to do that is some sort of hybrid cryptosystem leveraging something like RSA-KEM to encapsulate a key for a symmetric cipher like AES-GCM or ChaCha20Poly1305.
> 
> I’m not sure if there’s an off-the-shelf scheme for that in Rust, though.
> 
> If you have trouble finding one and don’t specifically require RSA but just general-purpose public key cryptography, there are several schemes that use elliptic curves.

OK , I'd tried other ways. tks
