### ISSUE TITLE
Confusing API naming

### ISSUE THREAD

**Issue by DuckDuckWhale** [RustCrypto/RSA#113]
Is it intended that to parse a PKCS#1 vs PKCS#8 key we should use `RsaPublicKeyDocument::from_pkcs1_der` and `RsaPublicKeyDocument::from_public_key_der` respectively? This seems confusing to me. The trait names are also inconsistent (`FromRsaPublicKey` vs `FromPublicKey`).

Also, one can simply use `RsaPublicKey::from_pkcs1_der` to construct one from PKCS#1, but must use `RsaPublicKey::from_pkcs1_public_key(RsaPublicKeyDocument::from_public_key_der().unwrap().public_key())` to construct one from PKCS#8. Maybe it should also implement the trait `pkcs8::FromPublicKey`?

**Comment by tarcieri** [comment]
> Is it intended that to parse a PKCS#1 vs PKCS#8 key we should use RsaPublicKeyDocument::from_pkcs1_der and RsaPublicKeyDocument::from_public_key_der respectively? This seems confusing to me.

It is confusing, but unfortunately, so are the surrounding standards.

First off, there's no such thing as a PKCS#8 public key. PKCS#8 is a standard for private keys. More modern versions allow storing a public/private keypair, but no PKCS#8 specification covers public keys in isolation.

The public key format is actually X.509 SubjectPublicKeyInfo, a.k.a. SPKI. It's unrelated to PKCS#8, but used in conjunction with it.

> The trait names are also inconsistent (FromRsaPublicKey vs FromPublicKey).

PKCS#1 is for RSA keys only. PKCS#8 supports multiple algorithms.

> Maybe it should also implement the trait pkcs8::FromPublicKey?

Yes, it should. This is something I was able to do a bit better when writing the `pkcs1` crate and would love to refactor `pkcs8` with as well, but it would be a breaking change and I haven't had time.

Also it'd be good to file issues against these here, as they're actually separate crates from `rsa`: https://github.com/rustcrypto/utils

**Comment by DuckDuckWhale** [comment]
Thanks for the explanation! Now it makes sense to me. I'm trying to update `rsa` from 0.3.0 to 0.5.0 in a project and encountered a compile error on `RSAPublicKey::from_pkcs8`. I'm not sure why the original code uses PKCS#8 and tried to find equivalent methods in 0.5.0 just to be safe but had some trouble digging through the docs. I wonder why 0.3.0 have [both `RSAPublicKey::from_pkcs1` and `RSAPublicKey::from_pkcs8`](https://docs.rs/rsa/0.3.0/rsa/struct.RSAPublicKey.html) if there's no such thing as a PKCS#8 public key? Same goes for `pkcs8` crate, why does it have `pkcs8::FromPublicKey::from_public_key_der`?

> Also it'd be good to file issues against these here, as they're actually separate crates from `rsa`: https://github.com/rustcrypto/utils

I see. This originated from upgrading `rsa` so I thought to ask here to get an idea first. I'll file issues there once I find out what's going on :P

**Comment by tarcieri** [comment]
>  I wonder why 0.3.0 have both RSAPublicKey::from_pkcs1 and RSAPublicKey::from_pkcs8 if there's no such thing as a PKCS#8 public key? Same goes for pkcs8 crate, why does it have pkcs8::FromPublicKey::from_public_key_der?

SPKI is commonly used as the public key counterpart to a PKCS#8 private key. The function which explicitly called it a PKCS#8 public key in `rsa` v0.3 is technically incorrect, however.

In the `pkcs8` crate, everything related to public keys is actually re-exports of the corresponding types from the [`spki`](https://docs.rs/spki) crate.

If you're just trying to parse a DER or PEM public key, I'd suggest looking at the examples in the `rsa` crate:

https://docs.rs/rsa/0.5.0/rsa/#pkcs8-rsa-key-encoding

Specifically, you should be able to call [`from_public_key_der`](https://docs.rs/pkcs8/0.7.5/pkcs8/trait.FromPublicKey.html#method.from_public_key_der) on `RsaPublicKey`, so long as you have [`rsa::pkcs8::FromPublicKey`](https://docs.rs/pkcs8/0.7.5/pkcs8/trait.FromPublicKey.html) in scope.

**Comment by DuckDuckWhale** [comment]
Oops, I missed the blanket implementation part. Thanks!
