### ISSUE TITLE
CryptoRng requirement for RsaPrivateKey generate function

### ISSUE THREAD

**Issue by aumetra** [RustCrypto/RSA#115]
Is there a reason why the `new` and `new_with_exp` function of the `RsaPrivateKey` struct don't require the randomness source to implement `CryptoRng`? 

Requiring the `CryptoRng` impl would discourage using low entropy randomness sources at the type level as well as make it more consistent with other RustCrypto crates. The `ecdsa` crate, for example, requires the `SigningKey` type to be generated from a randomness source that implements `CryptoRng`

**Comment by dignifiedquire** [comment]
Yes, while I like the idea of `CryptoRng` it is really painful when it comes to testing, as for example a common seeded RNG that is used for testing is https://docs.rs/rand_xorshift, which does not implement `CryptoRng`.

**Comment by str4d** [comment]
What I've done for testing purposes in other crates, is have the main public constructor be bound on `CryptoRng`, and then behind some testing-specific feature flag expose an underlying constructor that accepts any `Rng` (and it's named something obvious like `new_for_testing_only_not_for_production` so crate auditors can easily spot it).

**Comment by tarcieri** [comment]
You can always use `ChaCha8Rng` as a deterministic `CryptoRng`
