### ISSUE TITLE
Consider releasing 0.6 to be compatible with the other hash crates in their latest version (sha2, ...)

### ISSUE THREAD

**Issue by poliorcetics** [RustCrypto/RSA#137]

**Comment by tarcieri** [comment]
Would be good to get #120 addressed first (which is admittedly on me)

**Comment by tarcieri** [comment]
PR to update `pkcs1` and `pkcs8` here: https://github.com/RustCrypto/RSA/pull/139

**Comment by tarcieri** [comment]
Would be nice to figure out #135

**Comment by paolobarbolini** [comment]
Is there anything else blocking the final 0.6.0 release?

**Comment by newpavlov** [comment]
@dignifiedquire Do you plan any additional changes?

**Comment by dignifiedquire** [comment]
let’s just cut it

**Comment by dignifiedquire** [comment]
published, thanks for the patience
