### ISSUE TITLE
Compilling Error using RSA and SHA256 combination to verify

### ISSUE THREAD

**Issue by Neirth** [RustCrypto/RSA#140]
Hi guys, I'm trying to test the library combination of SHA256 and RSA to verify signatures made in this combination for a project.

When building the project, I get this wild error that I can't understand where it comes from or if I'm doing something wrong, since the documentation doesn't seem to explain this method very well.

> error[E0277]: the trait bound `CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<UTerm, B1>, sha2::digest::consts::B0>, sha2::digest::consts::B0>, sha2::digest::consts::B0>, sha2::digest::consts::B0>, sha2::digest::consts::B0>>>: digest::Update` is not satisfied
   --> src/container/file_format.rs:84:29
    |
84  | ...                   PaddingScheme::new_pss::<Sha256, _>(OsRng),
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `digest::Update` is not implemented for `CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<UTerm, B1>, sha2::digest::consts::B0>, sha2::digest::consts::B0>, sha2::digest::consts::B0>, sha2::digest::consts::B0>, sha2::digest::consts::B0>>>`
    |
    = note: required because of the requirements on the impl of `digest::digest::Digest` for `CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<UTerm, B1>, sha2::digest::consts::B0>, sha2::digest::consts::B0>, sha2::digest::consts::B0>, sha2::digest::consts::B0>, sha2::digest::consts::B0>>>`
note: required by a bound in `PaddingScheme::new_pss`
   --> /home/neirth/.cargo/registry/src/github.com-1ecc6299db9ec823/rsa-0.5.0/src/padding.rs:143:33
    |
143 |     pub fn new_pss<T: 'static + Digest + DynDigest, S: 'static + RngCore>(rng: S) -> Self {
    |                                 ^^^^^^ required by this bound in `PaddingScheme::new_pss`

The code that I have written to replicate this comes to be something similar to this, which is inspired by the unit test of the method.
```rust
file.seek(SeekFrom::Start(4)).unwrap();
file.read_exact(&mut signature_buff).unwrap();

let mut hasher = Sha256::new();

file.seek(SeekFrom::Start(4 + 128)).unwrap();
copy(&mut file, &mut hasher).unwrap();

match RsaPublicKey::read_public_key_pem_file(public_key) {
    Ok(rsa_public_key) => {
        return rsa_public_key.verify(
            PaddingScheme::new_pss::<Sha256, _>(OsRng),
            &hasher.finalize(),
            &signature_buff
        ).is_ok();
    }
    Err(_) => panic!("[Error]: Failed to process the file {}", public_key)
}
```
I may be missing something, but I can't find any type of reference to save me from the step.

**Comment by newpavlov** [comment]
What versions of `rsa` and `sha2` are you using?

**Comment by Neirth** [comment]
@newpavlov, now, I'm using these versions:

```toml
sha2 = "0.10.1"
rsa = "0.5.0"
```

**Comment by Neirth** [comment]
You were right, it was totally a problem of conflicting dependencies. Thanks so much for the help. :D
