### ISSUE TITLE
OAEP Padding doesn't compile

### ISSUE THREAD

**Issue by Aandreba** [RustCrypto/RSA#145]
When you put the example OAEP code into a new empty project, only importing ```rsa```, ```sha2``` and  ```rand```, the compiler throws an error when trying writing the following
```rust
let padding = PaddingScheme::new_oaep::<sha2::Sha256>();
```

The compiler error is ```the trait `digest::fixed::FixedOutputDirty` is not implemented for `CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, sha2::digest::typenum::UInt<sha2::digest::typenum::UInt<sha2::digest::typenum::UInt<sha2::digest::typenum::UInt<sha2::digest::typenum::UInt<sha2::digest::typenum::UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>>```

**Comment by newpavlov** [comment]
With `rsa v0.5` you should use `sha2 v0.9`, not the latest v0.10.

**Comment by Aandreba** [comment]
I'll try it later. If that's the case, it should be documented somewhere (perhaps it is and I just didn't find it)

**Comment by Aandreba** [comment]
> With `rsa v0.5` you should use `sha2 v0.9`, not the latest v0.10.

Okey, confirmed, that solved it. As I said, I think it would be nice if this was mentioned somewhere in the documentation, but that's just my opinion. Thank you very much for your help
