### ISSUE TITLE
how to read a private key from file or string?

### ISSUE THREAD

**Issue by aak1247** [RustCrypto/RSA#160]

**Comment by tarcieri** [comment]
## PKCS#1

Docs: https://docs.rs/rsa/latest/rsa/#pkcs1-rsa-key-encoding
`DecodeRsaPrivateKey`: https://docs.rs/pkcs1/0.3.3/pkcs1/trait.DecodeRsaPrivateKey.html

## PKCS#8

Docs: https://docs.rs/rsa/latest/rsa/#pkcs8-rsa-key-encoding
`DecodePrivateKey`: https://docs.rs/pkcs8/0.8.0/pkcs8/trait.DecodePrivateKey.html

**Comment by aak1247** [comment]
Thanks a lot!



| |
Yahui Liu
about.me/aak1247 |




---- 回复的原邮件 ----
| 发件人 | Tony ***@***.***> |
| 日期 | 2022年04月27日 20:45 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [RustCrypto/RSA] how to read a private key from file or string? (Issue #160) |

PKCS#1

Docs: https://docs.rs/rsa/latest/rsa/#pkcs1-rsa-key-encoding
DecodeRsaPrivateKey: https://docs.rs/pkcs1/0.3.3/pkcs1/trait.DecodeRsaPrivateKey.html

PKCS#8

Docs: https://docs.rs/rsa/latest/rsa/#pkcs8-rsa-key-encoding
DecodePrivateKey: https://docs.rs/pkcs8/0.8.0/pkcs8/trait.DecodePrivateKey.html
