### ISSUE TITLE
boring seems incompatible with rsa crate

### ISSUE THREAD

**Issue by dvc94ch** [RustCrypto/RSA#161]
assuming that the error is in boringssl as I've used the rsa crate in the past with "other" rsa implementations. the android debug bridge protocol uses boringssl which fails to validate rsa signatures. used `boring` to try to reproduce.

```rust
    #[test]
    fn test_sign() {
        let token = [0; 20];
        let private_key = RsaPrivateKey::new(&mut rand::rngs::OsRng, 2048).unwrap();
        let padding = PaddingScheme::new_pkcs1v15_sign(Some(Hash::SHA1));
        let signature = private_key.sign(padding, &token).unwrap();
        use rsa::pkcs8::EncodePublicKey;
        use rsa::pkcs1::der::Document;
        let public_key = RsaPublicKey::from(&private_key);
        //let public_key = public_key.to_public_key_pem(rsa::pkcs1::LineEnding::LF).unwrap();
        let public_key = public_key.to_public_key_der().unwrap();
        let public_key = public_key.as_der();
        unsafe {
            let public_key = boring_sys::RSA_public_key_from_bytes(public_key.as_ptr(), public_key.len());
            if public_key.is_null() {
                for err in boring::error::ErrorStack::get().errors() {
                    println!("{}", err);
                }
                panic!();
            }
            let res = boring_sys::RSA_verify(
                boring_sys::NID_sha1,
                token.as_ptr(),
                token.len(),
                signature.as_ptr(),
                signature.len(),
                public_key,
            );
            if res != 1 {
                for err in boring::error::ErrorStack::get().errors() {
                    println!("{}", err);
                }
                panic!();
            }
        };
    }
```

```
BAD_ENCODING

Code: 03000075
Loc: /home/dvc/.cargo/registry/src/github.com-1ecc6299db9ec823/boring-sys-2.0.0/deps/boringssl/src/crypto/bn_extra/bn_asn1.c:26
BAD_ENCODING

Code: 04000064
Loc: /home/dvc/.cargo/registry/src/github.com-1ecc6299db9ec823/boring-sys-2.0.0/deps/boringssl/src/crypto/rsa_extra/rsa_asn1.c:100
BAD_ENCODING

Code: 04000064
Loc: /home/dvc/.cargo/registry/src/github.com-1ecc6299db9ec823/boring-sys-2.0.0/deps/boringssl/src/crypto/rsa_extra/rsa_asn1.c:120
thread 'client::tests::test_sign' panicked at 'explicit panic', adb-rs/src/client.rs:532:1
```

cross posted here https://github.com/cloudflare/boring/issues/69

**Comment by tarcieri** [comment]
> BAD_ENCODING
>
> Code: 04000064
> Loc: /home/dvc/.cargo/registry/src/github.com-1ecc6299db9ec823/boring-sys-2.0.0/deps/boringssl/src/crypto/rsa_extra/rsa_asn1.c:120

This is an error in [`RSA_public_key_from_bytes`](https://github.com/google/boringssl/blob/f1c75347daa2ea81a941e953f2263e0a4d970c8d/src/crypto/rsa_extra/rsa_asn1.c#L114-L124)

This function [appears to want a PKCS#1 public key](https://commondatastorage.googleapis.com/chromium-boringssl-docs/rsa.h.html#RSA_public_key_from_bytes), but you are supplying a SPKI-encoded key as commonly used with PKCS#8.

Try serializing the key with [`to_pkcs1_der`](https://docs.rs/pkcs1/latest/pkcs1/trait.EncodeRsaPublicKey.html#tymethod.to_pkcs1_der) instead and see if that fixes the problem.

**Comment by dvc94ch** [comment]
In the meantime I got it working. There was a few confusing things about authentication in the adb protocol. One was this really weird custom public key encoding [0]. Then the reason I assumed the signature verification failed was because it will keep sending an auth1 packet until a signature in a auth2 packet succeeds or a new public key is sent in an auth3 packet. I assumed that a key registered via usb would also work via tcp, which seems not to be the case.

- [0] https://github.com/cloudpeers/xbuild/blob/511ff03206cdf2928d8a52224593e02d76e9c26d/mdb/src/adb/pubkey.rs#L21
