### ISSUE TITLE
`RsaPrivateKey` should implement `Hash`

### ISSUE THREAD

**Issue by Erik1000** [RustCrypto/RSA#165]
`RsaPublicKey` does implement `Hash` but `RsaPrivateKey` does not, why? `rsa` should conform to [`C-COMMON-TRAITS`](https://rust-lang.github.io/api-guidelines/interoperability.html#types-eagerly-implement-common-traits-c-common-traits).

**Comment by tarcieri** [comment]
This would expose private key material to an instance of `core::hash::Hasher`, which is not necessarily guaranteed to operate on the key material in constant-time.

It should be fine if the `Hasher` is `core::hash::SipHasher` as used by default, as that's a secure PRF. Potential leakage will vary for other algorithms.

**Comment by tarcieri** [comment]
All that said, an approach that could work and generally be safe would be hashing only the public components of `RsaPrivateKey`.

**Comment by dignifiedquire** [comment]
As long as we add some prefix, ensuring it hashes to something differently than the Public Key.
