### ISSUE TITLE
Bump `zeroize` to a higher version

### ISSUE THREAD

**Issue by imryao** [RustCrypto/RSA#169]
Hi there!

I'm using `rsa` with `aes-gcm-siv` and I've run into a cargo version conflict problem:

```
Execution failed (exit code 101).
/Users/mryao/.cargo/bin/cargo metadata --verbose --format-version 1 --all-features
stdout :     Updating crates.io index
error: failed to select a version for `zeroize`.
    ... required by package `num-bigint-dig v0.8.1`
    ... which satisfies dependency `num-bigint = "^0.8.1"` of package `rsa v0.7.0-pre`
    ... which satisfies dependency `rsa = "^0.7.0-pre"` of package `crypto-wasm-wxa v0.1.0 (/Users/mryao/IdeaProjects/crypto-wasm-wxa)`
versions that meet the requirements `^1.5` are: 1.5.7, 1.5.6, 1.5.5, 1.5.4, 1.5.3

all possible versions conflict with previously selected packages.

  previously selected package `zeroize v1.0.0`
    ... which satisfies dependency `zeroize = ">=1, <1.4"` of package `aes-gcm-siv v0.10.3`
    ... which satisfies dependency `aes-gcm-siv = "^0.10.3"` of package `crypto-wasm-wxa v0.1.0 (/Users/mryao/IdeaProjects/crypto-wasm-wxa)`

failed to select a version for `zeroize` which could resolve this conflict
```

It seems `rsa` is using an outdated version of `zeroize`, which is different from `aes-gcm-siv`.

So I'm wondering if we can bump `zeroize` to a higher `1.5.*` version.

Looking forward to your reply!

**Comment by tarcieri** [comment]
The problem is `num-bigint-dig` (a dependency of `rsa`) requires `zeroize` 1.5, whereas `aes-gcm-siv` v0.10.3 requires `<1.4`. So it's `aes-gcm-siv` that's out-of-date.

There's a tracking issue here: https://github.com/RustCrypto/utils/issues/723

To get around this you can use `aes-gcm-siv` v0.11.0-pre.2. We'll have a final release out soon.
