### ISSUE TITLE
Having a `MAX_PUB_EXPONENT` makes this crate unusable with some applications

### ISSUE THREAD

**Issue by AppleSheeple** [RustCrypto/RSA#199]
Some applications use very large numbers, including ones from [factoring challenges](https://en.wikipedia.org/wiki/RSA_numbers), for the exponent part of the key.

Having a `MAX_PUB_EXPONENT` makes this crate unusable with such applications without using a patched source tree.

If the concern is compatibility with platforms that do enforce such limits, then the limit should be optional, and the purpose of it should be stated explicitly, IMHO.

**Comment by tarcieri** [comment]
The concern is potential misuse: increasing the size of the public exponent `e` decreases the size of the private exponent `d`. In practice there is no need for a public exponent larger than 65,537 (and really 3 is sufficient with proper padding).

Or in other words: using a larger `e` only subtracts from the overall security of the key.

If `d` is smaller than the 4th root of `n`, it can be recovered using [Weiner's attack](https://en.wikipedia.org/wiki/Wiener%27s_attack).

For this reason it's fairly common for RSA libraries to enforce a maximum size on the public exponent.

**Comment by AppleSheeple** [comment]
Sure. But in practice, sometimes you can't control the exponent used by others, or by default/policy. And the limit imposed is still too small.

For example, I have a use-case where 1024 bit long values are used for `n`. And a fixed 212 bit long exponent is used. `d` still doesn't get *small*.

**Comment by dignifiedquire** [comment]
We could add another hazmat type feature, which allows larger sized exponents, still preventing default users from using larger exponents by default.

**Comment by dignifiedquire** [comment]
I am personally very much in favor of allowing potentially unsafe features, as long as the public default api doesn't expose it. To avoid exactly the issue of forks and patches that are potentially much more problematic (and just make it harder for folks to move forward)

**Comment by tarcieri** [comment]
Yeah, this somewhat exists already with the (unreleased) `RsaPublicKey::new_with_max_size`

We could relax that into a fully unchecked version

**Comment by tarcieri** [comment]
I opened #206 which adds `RsaPublicKey::new_unchecked` which bypasses all checks.
