### ISSUE TITLE
Deterministic key pair from a seed

### ISSUE THREAD

**Issue by elielnfinic** [RustCrypto/RSA#209]
Hi everybody,

I know that in order to have strong keys, we need to have two random numbers but on the other hand, it is difficult to recover a lost key. Is there a possibility to allow generation of keys based on a deterministic seed as it is done in BIP-32/39 to allow easy recovery of the keys?

Thank you.

**Comment by elielnfinic** [comment]
I was able to generate deterministic RSA private key using `RsaPrivateKey::from_components`.
So, I am closing this issue.

**Comment by tarcieri** [comment]
@elielnfinic FYI, if this is helpful:

[`RsaPrivateKey::new`](https://docs.rs/rsa/latest/rsa/struct.RsaPrivateKey.html#method.new) accepts an `RngCore + CryptoRng` argument.

You can use e.g. [`ChaCha8Rng`](https://docs.rs/rand_chacha/latest/rand_chacha/struct.ChaCha8Rng.html) for this, which produces a random keystream from a 256-bit seed.

**Comment by elielnfinic** [comment]
Thanks @tarcieri, I was able to generate deterministic pair with `ChaCha8Rng`.
I am using [bip32](https://docs.rs/bip32/latest/bip32/) library to generate seed from `mnemonic` but it generates  a [u8; 64] though ChaCha8Rng accepts [u8; 32]. Can you suggest any library to generate that outputs [u8; 32] from a mnemonic phrase?

**Comment by elielnfinic** [comment]
I have been able to overcome this issue by using `ChaCha8Rng::seed_from_u64` by hashing the mnemonic to a `u64` integer.

**Comment by tarcieri** [comment]
A `u64` has insufficient entropy to be secure. You really need to initialize it with 256-bits/32-bytes entropy.

BIP32 derivation should produce two values: a 32-byte derived secret, and a 32-byte “chain code”. You can use the 32-byte secret as the key, ignoring the “chain code”

**Comment by elielnfinic** [comment]
Sure, thank you @tarcieri. 
I really appreciate.
