### ISSUE TITLE
Add DER encoding/decoding support

### ISSUE THREAD

**Issue by caelunshun** [RustCrypto/RSA#21]

**Comment by caelunshun** [comment]
I've hacked together a quick implementation of this [here](https://github.com/caelunshun/rsa-der/blob/master/src/lib.rs).

**Comment by caelunshun** [comment]
I've implemented a quick version of this at https://github.com/caelunshun/rsa-der.

**Comment by tarcieri** [comment]
You might want to check out @alex's `asn1` crate (revamp): https://github.com/alex/rust-asn1/pull/54

**Comment by alex** [comment]
FYI, I intend to merge and release that soon, hopefully the next week. It
doesn't yet have encode support though.

**Comment by newpavlov** [comment]
Also I think it will be worth to check out the `ring` code as well (although note the license), it was proposed to split this code into a different crate in briansmith/ring#586, but unfortunately without much success.

**Comment by tarcieri** [comment]
Re: that, there's [`derp`](https://crates.io/crates/derp), but it's only a parser

**Comment by roblabla** [comment]
In linkle I ended up using `pem` and `yasna` to parse private keys generated with openssl: https://github.com/MegatonHammer/linkle/blob/npdm/src/format/npdm.rs#L323

The ASN.1 key format is standardized in RFC 3447, Appendix C. Look for "RSAPrivateKey".

**Comment by tarcieri** [comment]
@roblabla oh joy, I think you're talking about the "SSLeay format". Does it start with this?

```
-----BEGIN RSA PRIVATE KEY-----
```

If so, that's a bespoke PEM encoding of PKCS#1 (i.e. RFC 3447) added to SSLeay, the library which would eventually become OpenSSL.

Personally I'd suggest using PKCS#8 (RFC 5208/5958) instead unless you really, really need to support the SSLeay format for something. These keys start with:

```
-----BEGIN PRIVATE KEY-----
```

or

```
-----BEGIN ENCRYPTED PRIVATE KEY-----
```

PKCS#8 has the advantage of being reusable for things like ECDSA (and even Ed25519).

**Comment by roblabla** [comment]
Well I mostly parsed what openssl gave me as an output - which is PKCS#1. I suppose we can get openssl to give us a PKCS#8? (Probably using `openssl genpkey` instead of `openssl genrsa`). I’ll look into it.

**Comment by tarcieri** [comment]
If you're using the OpenSSL CLI, the PKCS#8 functionality is under `openssl pkcs8`

**Comment by nickray** [comment]
@tarcieri would you know what's the current state of `no_std` DER? I need to encode some FIDO2 stuff (signatures, *maybe* certificates), would lightly prefer to not do things too manually, but also not pull in some huge ASN.1 dependency. The things I've surfaced are all `std`.

cf. https://github.com/heartsucker/derp/issues/6

**Comment by tarcieri** [comment]
For signatures, you could look at potentially translating the relevant BearSSL C code. That’s what I did in the `ecdsa` crate.

For certificates, perhaps consider @geal’s `cookie-factory`. If you’re talking about X.509 certificates, you might be able to add `no_std` support to @str4d’s x509.rs:

https://github.com/str4d/x509.rs

**Comment by nickray** [comment]
> For signatures, you could look at potentially translating the relevant BearSSL C code. That’s what I did in the `ecdsa` crate.

Ah perfect, your conversions there are exactly what I need, will add them to `nisty`. Thanks!

**Comment by tarcieri** [comment]
@nickray you might also look at:

https://www.bearssl.org/gitweb/?p=BearSSL;a=blob_plain;f=src/rsa/rsa_pkcs1_sig_pad.c
https://www.bearssl.org/gitweb/?p=BearSSL;a=blob_plain;f=src/rsa/rsa_pss_sig_pad.c

It looks like BearSSL just hardcodes the relevant ASN.1 DER

**Comment by nickray** [comment]
I ended up with a manual mashup of your stuff and derp stuff, I only need ECDSA DER encoding (as the certificates can be hardcoded): https://github.com/nickray/usbd-ctaphid/blob/main/src/derpy.rs. Not super-efficient, but at least it's readable (at least for my mind). Very much hoping I don't have to dig much deeper into this, as I find myself wondering how many semi-efficient pseudo-consistent serialization formats mankind has to come up with...

Funny how Microsoft has the best docs I know of on how this is supposed to work:
- https://docs.microsoft.com/en-us/windows/win32/seccertenroll/about-encoded-length-and-value-bytes
- https://docs.microsoft.com/en-us/windows/win32/seccertenroll/about-integer

**Comment by dignifiedquire** [comment]
I think most of this is fixed with https://github.com/RustCrypto/RSA/pull/38

Could folks confirm if their favorite format is supported by this, or if they are still missing one?

**Comment by kitlith** [comment]
@dignifiedquire afaict that PR exposes parsing PEM files (#20) but does not directly expose parsing DER. You *could* parse DER by turning it into a PEM and then feeding it through, but it would be nice if you could just feed it the bytes directly.

**Comment by tarcieri** [comment]
Seems like we can close this issue then?
