### ISSUE TITLE
sample can not be compiled 

### ISSUE THREAD

**Issue by xiaoquanju** [RustCrypto/RSA#213]
https://docs.rs/rsa/0.7.0/rsa/       
sample can not be compiled 
 
  let mut rng = rand::thread_rng();
  let bits = 2048;
  let private_key = RsaPrivateKey::new(&mut rng, bits).expect("failed to generate a key");
  let public_key = RsaPublicKey::from(&private_key);

err message is:

error[E0277]: the trait bound `ThreadRng: rsa::rand_core::CryptoRng` is not satisfied
   --> src\main.rs:30:23
    |
30  |     let private_key = RsaPrivateKey::new(&mut rng, bits).expect("failed to generate a key");
    |                       ^^^^^^^^^^^^^^^^^^ the trait `rsa::rand_core::CryptoRng` is not implemented for `ThreadRng`
    |
    = help: the following other types implement trait `rsa::rand_core::CryptoRng`:
              &'a mut R
              BlockRng<R>
              Box<R>
              rand::rngs::adapter::reseeding::ReseedingRng<R, Rsdr>
              rand::rngs::std::StdRng
              rand::rngs::thread::ThreadRng
              rand_chacha::chacha::ChaCha12Core
              rand_chacha::chacha::ChaCha12Rng
            and 5 others
note: required by a bound in `rsa::RsaPrivateKey::new`
   --> C:\Users\quanjuxiao\.cargo\registry\src\github.com-1ecc6299db9ec823\rsa-0.7.0\src\key.rs:283:29
    |
283 |     pub fn new<R: RngCore + CryptoRng>(rng: &mut R, bit_size: usize) -> Result<RsaPrivateKey> {
    |                             ^^^^^^^^^ required by this bound in `rsa::RsaPrivateKey::new`

**Comment by newpavlov** [comment]
Check your version of `rand`. It should be v0.8.

**Comment by xiaoquanju** [comment]
> rand
solved thanks

**Comment by sp1ff** [comment]
This would be worth noting in the documentation.
