### ISSUE TITLE
Use `BigUint` for the Signature internal representations

### ISSUE THREAD

**Issue by lumag** [RustCrypto/RSA#220]
Ideally we could replace the internal representation of a `Signature`s with a `BigUint` now, which would eliminate the need for an intermediate `Box<[u8]>` when signing/verifying.

_Originally posted by @tarcieri in https://github.com/RustCrypto/RSA/pull/217#discussion_r1009872868_

**Comment by tarcieri** [comment]
cc @npmccallum 

There are many APIs that currently take a slice which would need at least an equivalent API which operates on a `BigUint`.

I think we could potentially consider removing some of the old APIs from the public API as well.

**Comment by tarcieri** [comment]
Implemented in #298 and #300
