### ISSUE TITLE
Should `PaddingScheme` be a trait instead of an enum?

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/RSA#226]
Looking at issues like #215 it seems like requirements of certain variants are making the others somewhat harder to use.

The `PKCS1v15Encrypt` and `PKCS1v15Sign` have relatively minimal requirements with `PKCS1v15Encrypt` having no members whatsoever, whereas `OAEP` and `PSS` both need `Box<dyn DynDigest + Send + Sync>`.

Having a trait would allow the impls to live in e.g. `pkcs1v15` and `pss` modules as well, whereas right now the `pkcs1v15` module only exposes encryption-related functionality.

**Comment by newpavlov** [comment]
Maybe it's better to completely remove `PaddingScheme` and instead introduce separate padding-specific methods on `RsaPrivateKey`?

**Comment by tarcieri** [comment]
@newpavlov both the public and private key need padding-related functionality. The public key needs to generate a padded message for encryption, and verify the padding with a signature, with the inverse true for private keys.

**Comment by lumag** [comment]
I'd second @newpavlov here. I'd drop the `PaddingScheme` completely instead. For the sign/verify ops we have `Signer` / `Verifer` families which do not need `PaddingScheme`. So, I think, it would be logical to add `Encryptor` / `Decryptor` and drop the PS.

**Comment by lumag** [comment]
@tarcieri I'd start with something like https://github.com/RustCrypto/RSA/pull/245

**Comment by tarcieri** [comment]
It's going to be a nightmare to rebase #244 on that :cry:

It would've been better if you started with #244 as the base.

**Comment by lumag** [comment]
@tarcieri well, I branched off the trunk on purpose. IMHO there is no point in having `SignatureScheme` if we can drop it first.

**Comment by lumag** [comment]
@tarcieri @newpavlov @dignifiedquire  Also I think that we should make encryption/decryption follow the `Signer` API. In other words, have a separate `Encryptor` / `Decryptor` traits, implement padding-specific keys and drop `PaddingScheme` completely.

**Comment by lumag** [comment]
I implemented my ideas as #246

**Comment by tarcieri** [comment]
Resolved by #244
