### ISSUE TITLE
PublicKey To PEM Question 

### ISSUE THREAD

**Issue by WingZer0o** [RustCrypto/RSA#229]
I realize that this is not even a 1.0 library yet had to dig through some source. Is it possible to export a `RsaPublicKey` to a pem string using `to_pkcs8_pem()` like I was able to do here with the private key?

```rust
fn generate_rsa4096_private_key() -> String {
    let mut rng = OsRng;
    let bits = 4096;
    let priv_key = RsaPrivateKey::new(&mut rng, bits).expect("failed to generate a key");
    return priv_key.to_pkcs8_pem(rsa::pkcs8::LineEnding::LF).unwrap().to_string();
}

**Comment by WingZer0o** [comment]
Little late. This is the first time I am diving into the underlying code for such a library and got the formatting a little confused. However, here is the code that I was using this might be helpful in someway for documentation for someone else. 

```rust
fn rsa4096_testing(pem_string: &str) -> String {
    let mut rng: OsRng = OsRng;
    let bits: usize = 4096;
    let priv_key = RsaPrivateKey::from_pkcs8_pem(pem_string).unwrap();
    let pub_key = priv_key.to_public_key();
    let encrypted = pub_key.to_pkcs1_pem(rsa::pkcs1::LineEnding::LF).unwrap().to_string();
    return encrypted;
}

**Comment by tarcieri** [comment]
Seems like you got this figured out then

**Comment by WingZer0o** [comment]
Yes.
