### ISSUE TITLE
Cannot decrypt values with public key

### ISSUE THREAD

**Issue by ssddOnTop** [RustCrypto/RSA#230]
If Bob with keypair (pub1, priv1) and Alice with keypair (pub2, priv2) wants to verify that the message is from the legit source, they can do something like:

c1 = encrypt message with bob's public key
c2 = encrypt c1 with alice's private key

send message

c3 = decrypt c2 with alice's public key
c4 = decrypt c3 with bob's priv key

But it's not available with this dependency, please add decryption with public key as well

**Comment by tarcieri** [comment]
Dup of #86
