### ISSUE TITLE
Can I encode the objects RsaPrivateKey and RsaPublicKey?

### ISSUE THREAD

**Issue by alk0x1** [RustCrypto/RSA#232]
Is possible to encode the `RsaPrivateKey ` and `RsaPublicKey` to base58 or base64 for example?
I want to generate the two keys and use as a wallet but I have no idea how to encode the keys in that format.

**Comment by tarcieri** [comment]
The main encodings for keys this crate supports are PKCS#1 and PKCS#8:

- https://docs.rs/rsa/latest/rsa/#pkcs1-rsa-key-encoding
- https://docs.rs/rsa/latest/rsa/#pkcs8-rsa-key-encoding

Those are traditionally encoded as PEM, which is Base64 encapsulated in e.g. `-----BEGIN PUBLIC KEY-----` boundaries
