### ISSUE TITLE
Confusion over `pkcs1v15::VerifyingKey::new` vs `::new_with_prefix`

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/RSA#238]
In #234 we had some people confused about signature verification failing with `::new`, and they had trouble discovering `::new_with_prefix`.

It would be good to either improve the documentation here, or eliminate the distinction between `::new` and `::new_with_prefix` and automatically determining if the prefix is needed (e.g. based on the OID of the provided digest).

It seems like other RSA libraries are able to make this determination automatically.

**Comment by dignifiedquire** [comment]
I think it would be great if we had 

- `new()` -> determines it automatically
- `new_prefix(p: Prefix)` explicitly expects a prefix or not. With `enum Prefix { Yes, No }` (names can be bikeshedded) for when you want to enforce one or the other.

**Comment by tarcieri** [comment]
I think part of the rationale for the current split is avoiding the need to have an `AssociatedOid` on the digest used.

Looking at [RFC8017 Appendix 2.4](https://www.rfc-editor.org/rfc/rfc8017#appendix-A.2.4), I'm unclear under what circumstances the OID can actually be omitted?

So perhaps the current `new` should be renamed to something like `new_unprefixed`, and `new_with_prefixed` should be renamed to `new`?
