### ISSUE TITLE
output signature into provided [u8]

### ISSUE THREAD

**Issue by stevedw** [RustCrypto/RSA#289]
Hi,
Is it possible to add a method to output the sig directly into a provided mut slice rather than return a sig for use cases where it would be better not to have to do a copy fromt he result each time?

Or if it exists I seme to be missing it in the docs.

**Comment by tarcieri** [comment]
There is no corresponding API on `BigUint` which provides this functionality to my knowledge

**Comment by tarcieri** [comment]
Also note that as of #220 both `pkcs1v15::Signature` and `pss::Signature` are wrappers for `BigUint`, if you're worried about an extra round trip to bytes.

That said, without an upstream API we can't implement this. I'd suggest opening an upstream issue.
