### ISSUE TITLE
How to create a Sha1 Signature?

### ISSUE THREAD

**Issue by thep0y** [RustCrypto/RSA#363]
Currently only Sha2 implements the AssociatedOid trait?
```rust
let signature = Pkcs1v15Sign::new::<Sha256>(); // => OK
let signature = Pkcs1v15Sign::new::<Sha1>(); // => the trait bound `Sha1Core: AssociatedOid` is not satisfied
```

**Comment by tarcieri** [comment]
You either need to enable the `sha1` feature of `rsa` and import it as `rsa::sha1::Sha1` or you need to enable the `oid` feature of `sha1`.

This will hopefully be a bit more automatic in the next release of `sha1`/`sha2`.
