### ISSUE TITLE
how to sign message by MD5withRSA?

### ISSUE THREAD

**Issue by aa51513** [RustCrypto/RSA#365]
I looked back and forth in the rsa crate documentation and unfortunately I didn't find anything related to it,

I think I need some help

**Comment by tarcieri** [comment]
I'll assume you want a PKCS#1v1.5 signature.

The [`rsa::pkcs1v15::SigningKey`](https://docs.rs/rsa/latest/rsa/pkcs1v15/struct.SigningKey.html) type is generic around a digest, e.g. `rsa::pkcs1v15::SigningKey<md5::Md5>`.

You'll need to enable the `oid` feature of `md5` in your `Cargo.toml` (for now, it will be automatic in the next release):

```toml
md5 = { package = "md-5", version = "0.10", features = ["oid"] }
```
