### ISSUE TITLE
Splitting up crate to reduce advisory blast radius?

### ISSUE THREAD

**Issue by ctz** [RustCrypto/RSA#395]
As someone who wants to do what I think are reasonable and defensible uses of RSA (that is: RSASSA-PSS and RSASSA-PKCS1-v1_5) it would be great if there was a crate for that. But without bringing along the inevitable, infinite future security advisories for a crate that includes raw RSA, RSAES-PKCS1-v1_5, etc.

I think that could be done along protocol lines (eg, "rsa-signing" and "rsa-hazmat" crates?) or in an opinionated way (eg, "rsa-ok", "rsa-hazmat" crates?). The existing "rsa" crate could just reexport everything from these, perhaps?

**Comment by tarcieri** [comment]
FWIW, the Marvin Attack enables signature forgeries with RSASSA-PKCS#1v1.5 (i.e. BB'06-style)

The recent advisory affects all private key operations and allows a network attacker to recover either decryption or signing keys. Making modpow constant time (#394) will prevent key recovery but we still won't have fully mitigated the Marvin Attack which will still allow for both decryption and signature forgeries.

Constant-time modpow should enable safe use of OAEP or PSS, however.

We will continue to look into what can be done for PKCS#1v15 (e.g. moving to a pseudorandom rejection symbol for padding failures), however this is merely the latest in a long line of attacks which points to it being fundamentally flawed (see also The 9 Lives of Bleichenbacher's CAT).

(FWIW, this attack impacted many RSA libraries, many of which like the `rsa` crate are still vulnerable or have only partially mitigated it)

**Comment by tarcieri** [comment]
Yeah, due to #19 there's timing variability from signature operations which can leak the private key

**Comment by tarcieri** [comment]
Going to close this as splitting up the crate would not help for at least this specific incident
