### ISSUE TITLE
the function or associated item `new` exists for struct `SigningKey<CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<..., ...>, ...>, ...>, ...>>>`, but its trait bounds were not satisfied [E0599]

### ISSUE THREAD

**Issue by trouvaille2023** [RustCrypto/RSA#401]
The code I copied from the official documentation will also generate errors. If there are any issues with the official documentation, what is the reference value when using it. How can I fix this error?

In the example, `use rsa:: sha2:: {Digest, Sha256};` is used, But the latest version of `rsa` does not include `sha2`

version: 0.9.6

Official example code:
<img width="987" alt="image" src="https://github.com/RustCrypto/RSA/assets/44250675/251e4769-8565-4062-8358-b9f0e0be78bd">

when I copy:
<img width="1616" alt="image" src="https://github.com/RustCrypto/RSA/assets/44250675/01a2c6ea-36c3-46a9-a5c6-120989e56986">

When I build it:
<img width="1655" alt="image" src="https://github.com/RustCrypto/RSA/assets/44250675/4cb56f19-7745-419c-b82d-e92be3987132">

**Comment by tarcieri** [comment]
Note that the top of the documentation says the `sha2` feature of the `rsa` crate must be enabled, but you have not enabled it.

> If there are any issues with the official documentation, what is the reference value when using it.

Rust documentation is doctested, and we run those doctests in CI, so the examples are "guaranteed" to work, at least if the relevant features are enabled.

**Comment by trouvaille2023** [comment]
> Note that the top of the documentation says the `sha2` feature of the `rsa` crate must be enabled, but you have not enabled it.
> 
> > If there are any issues with the official documentation, what is the reference value when using it.
> 
> Rust documentation is doctested, and we run those doctests in CI, so the examples are "guaranteed" to work, at least if the relevant features are enabled.

Thank you, But I did not see from the official documentation that sha2 needs to be enabled,And When I enable it, it is worked.

**Comment by tarcieri** [comment]
>  I did not see from the official documentation that sha2 needs to be enabled

<img width="987" alt="290379150-251e4769-8565-4062-8358-b9f0e0be78bd" src="https://github.com/RustCrypto/RSA/assets/797/8223d0f1-685f-416c-9f0a-2695793e32a1">

**Comment by trouvaille2023** [comment]
> > I did not see from the official documentation that sha2 needs to be enabled
> 
> <img alt="290379150-251e4769-8565-4062-8358-b9f0e0be78bd" width="987" src="https://private-user-images.githubusercontent.com/797/290383621-8223d0f1-685f-416c-9f0a-2695793e32a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjIwNDYsIm5iZiI6MTcwMjUyMTc0NiwicGF0aCI6Ii83OTcvMjkwMzgzNjIxLTgyMjNkMGYxLTY4NWYtNDE2Yy05ZjBhLTI2OTU3OTNlMzJhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQwMjQyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWUwNzM5Nzc1YmUyNDBjNjY2MzdjNDhmMjgyM2RjZDNiOGUxMmU1YjdjYmMwMDE5ZGYxOTYyNWJhMTUyZWM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G5DvaXe8phoNN51_m90i-fBbgd60TU_rUBiQg-RsOOo">



> > I did not see from the official documentation that sha2 needs to be enabled
> 
> <img alt="290379150-251e4769-8565-4062-8358-b9f0e0be78bd" width="987" src="https://private-user-images.githubusercontent.com/797/290383621-8223d0f1-685f-416c-9f0a-2695793e32a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjIwNDYsIm5iZiI6MTcwMjUyMTc0NiwicGF0aCI6Ii83OTcvMjkwMzgzNjIxLTgyMjNkMGYxLTY4NWYtNDE2Yy05ZjBhLTI2OTU3OTNlMzJhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQwMjQyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWUwNzM5Nzc1YmUyNDBjNjY2MzdjNDhmMjgyM2RjZDNiOGUxMmU1YjdjYmMwMDE5ZGYxOTYyNWJhMTUyZWM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G5DvaXe8phoNN51_m90i-fBbgd60TU_rUBiQg-RsOOo">

My mistake, thank you for your guidance.
