### ISSUE TITLE
Support `From<_> for &RsaPublicKey` and `From<_> for &RsaPrivateKey` for relevant types

### ISSUE THREAD

**Issue by LWEdslev** [RustCrypto/RSA#426]
For example if I have a `pss::VerifyingKey` and a function `fn foo(key: &RsaPublicKey)` I currenctly have to do this:
```Rust
let key: VerifyingKey<Sha256> = ....;
foo(&key.clone().into()); // if we don't clone here it is moved
```
whereas a pretty simple implementation could make it
```Rust
let key: VerifyingKey<Sha256> = ....;
foo((&key).into());
```
the implementation could be something like:
```Rust
impl<'a, D> From<&'a VerifyingKey<D>> for &'a RsaPublicKey
where
    D: Digest,
{
    fn from(key: &'a VerifyingKey<D>) -> Self {
        &key.inner
    }
}

```

**Comment by tarcieri** [comment]
Use [`AsRef`](https://docs.rs/rsa/latest/rsa/pss/struct.SigningKey.html#impl-AsRef%3CRsaPrivateKey%3E-for-SigningKey%3CD%3E)
