### ISSUE TITLE
how to decrypt with public key

### ISSUE THREAD

**Issue by imgoby** [RustCrypto/RSA#427]
In java, we can decrypt with public key. but in Rust,how to decrypt with public key?

server: encrypt with private key
client: want to decrypt with public key.

how to resolve?

**Comment by tarcieri** [comment]
Dup of: #86 #231

**Comment by imgoby** [comment]
Sorry,I could not find any refer code.Could you give me some advice method?

**Comment by tarcieri** [comment]
Per the linked issues this is not a feature we plan on implementing outside of a well-specified construction like #231
