### ISSUE TITLE
there is an associated function `from_pkcs8_pem` with a similar name

### ISSUE THREAD

**Issue by OstrichRunning** [RustCrypto/RSA#430]
let mut pem = String::new();
let private_key = RsaPrivateKey::from_pkcs1_pem(&pem)?;

**Comment by tarcieri** [comment]
Yes? PKCS#1 and PKCS#8 are two different standards for encoding RSA keys. PKCS#8 is a newer format and acts as a wrapper for the older PKCS#1, which was RSA only.

What is your specific concern?
