### ISSUE TITLE
Marvin Attack: potential key recovery through timing sidechannels

### ISSUE THREAD

**Issue by HZzz2** [RustCrypto/RSA#457]
![image](https://github.com/user-attachments/assets/9c12b104-596c-4de2-bedf-2e92a23a5093)

Run cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 664 security advisories (from /home/runner/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (315 crate dependencies)
error: 1 vulnerability found!
Crate:     rsa
Version:   0.9.6
Title:     Marvin Attack: potential key recovery through timing sidechannels
Date:      2023-11-22
ID:        RUSTSEC-2023-0071
URL:       https://rustsec.org/advisories/RUSTSEC-2023-0071
Severity:  5.9 (medium)
Solution:  No fixed upgrade is available!
Dependency tree:
rsa 0.9.6
├── ssh-key 0.6.7
│   ├── russh-keys 0.45.0
│   │   ├── russh 0.45.0
│   │   │   └── async-ssh2-tokio 0.8.12
│   │   │       └── tgbot-app 0.2.13
│   │   └── async-ssh2-tokio 0.8.12
│   └── russh 0.45.0
└── russh-keys 0.45.0

Error: Process completed with exit code 1.

**Comment by tarcieri** [comment]
Dup of #19
