### ISSUE TITLE
serde1 vs serde feature (crates.io package vs GitHub source code)

### ISSUE THREAD

**Issue by tpmccallum** [RustCrypto/RSA#46]
Hi,
I notice that if using the crates dot io package, the following type of error occurs
```
the trait serde::ser::Serialize is not implemented for rsa::RSAPrivateKey
```
In this instance the Cargo.toml file is using the `serde` feature. For example
```
[dependencies]
rsa = { version = "^0.2", features = ["serde"] }
```
The GitHub source code [1] and config [2] choose `serde` over `serde1`. I believe that `serde1` is deprecated.

If the following dependency in the Cargo.toml file is used the issue is resolved.
```
rsa = { version = "^0.2", features = ["serde1"] }
```
For example the private key can be easily serialised like this
```
use serde_json;
extern crate rand;
extern crate rsa;
use rand::rngs::OsRng;
use rsa::{RSAPrivateKey};
fn main() {
    let mut rng = OsRng;
    let bits = 2048;
    let key = RSAPrivateKey::new(&mut rng, bits).expect("failed to generate a key");
    let as_json_string = serde_json::to_string(&key).unwrap();
    println!("{:?}", as_json_string);
}
```
My main observation is that the crate is out of alignment/sync with the GitHub code, config and documentation. If the crate was updated then users would be able to use the following to enable the optional serde feature.
```
[dependencies]
rsa = { version = "^0.2", features = ["serde"] }
```

Hope this helps.

Kind regards
Tim

[1] https://github.com/RustCrypto/RSA/blob/master/src/key.rs#L51
[2] https://github.com/RustCrypto/RSA/blob/master/Cargo.toml#L59

**Comment by dignifiedquire** [comment]
thanks, the reason for this is that no new version has yet been published to crates.io, once that happens this will be resolved

**Comment by dignifiedquire** [comment]
Should be all fixed
