### ISSUE TITLE
subtle 2.3 MSRV is 1.41+

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/RSA#65]
subtle 2.3's MSRV is 1.41+. This is causing the build to break, since CI's MSRV is 1.36:

https://github.com/RustCrypto/RSA/pull/64/checks?check_run_id=1146119487

@dignifiedquire any preferences on how to address this? Seems we either need to lock to earlier releases of `subtle` or bump MSRV (personally I'd prefer the latter)

**Comment by dignifiedquire** [comment]
This is unfortunate. I would suggest doing a patch release pinning the version, and then a breaking release withe the updated version and new msrv.

**Comment by tarcieri** [comment]
#71 pins `subtle` and gets CI passing again.

**Comment by dignifiedquire** [comment]
fixed on `master`
