### ISSUE TITLE
Add a tutorial on intro page

### ISSUE THREAD

**Issue by AlscadIngenierie** [RustCrypto/RSA#7]
We could add how to use this crate : 

dependency to add in cargo.toml file
how to import the package in our own crate ?
how to generate private and public keys ?
how to access them and convert them into std::string ?
how to encrypt with the public key ?
how to decrypt with the private key ?

**Comment by dignifiedquire** [comment]
yes, agreed this would be great to have.

**Comment by dignifiedquire** [comment]
I added a basic example of encryption as a starting point to the readme

**Comment by builat** [comment]
Please could you expose example of from_components usage?

**Comment by dignifiedquire** [comment]
@builat is there a specific issue with that, you can see an example of it here: https://github.com/RustCrypto/RSA/blob/master/src/key.rs#L547

**Comment by builat** [comment]
@dignifiedquire Well no specific issue. But if you have to use RSA for the first time in your life you need to perform some kind of resaerch and do few more mental loops before you understand that you have to perform specific calculations for n,e,d and fi(n) and not just insert just prime numbers.

Anyway awsome job! and thnx for what you done.

**Comment by newpavlov** [comment]
I think it will be much better to link some good external materials instead of trying to squeeze all good-to-know knowledge to the crate docs.

**Comment by dignifiedquire** [comment]
My ideal state is to have proper doc comments on the individual methods, which link to the core definitions on wikipedia + other reference material, in addition to have usage examples.

**Comment by builat** [comment]
@newpavlov totaly agree for example best material for me was : https://www.di-mgt.com.au/rsa_alg.html

**Comment by skaunov** [comment]
I wonder if this issue is still relevant, and what methods needs attention from this angle. Especially regarding PKCS1v15 encryption. 

For example is it needed to describe why there two modules for padding, and one of them exposes only signatures `struct`s?

**Comment by tarcieri** [comment]
I also opened #226 with the suggestion of refactoring `PaddingScheme` into a trait, in which case the `PKCS1v15Encrypt` padding could be a `struct` that lives in e.g. `rsa::pkcs1v15::EncryptionPadding`.

**Comment by tarcieri** [comment]
Going to call this addressed by the current usage examples.

If there are specific things missing, please open new issues.
