### ISSUE TITLE
rsa is not compatible with rand 0.8.0

### ISSUE THREAD

**Issue by brmmm3** [RustCrypto/RSA#81]
If I update my dependency of rand from 0.7.3 to 0.8.0 I get the following error:

the trait bound `rand::rngs::OsRng: rand_core::RngCore` is not satisfied  the trait `rand_core::RngCore` is not implemented for `rand::rngs::OsRng`  note: required because of the requirements on the impl of `rand::Rng` for `rand::rngs::OsRng`

I'm using rsa 0.3.0.

**Comment by alechenthorne** [comment]
This seems to require that num-bigint is updated to rand 0.8 first and I've added an [issue in that project](https://github.com/dignifiedquire/num-bigint/issues/23).

**Comment by dignifiedquire** [comment]
Still waiting a little bit longer to propagate this through libraries, breaking `rand` changes are quite painful and dividing in the ecosystem. Last time around it took months for the ecosystem to rally behind the latest version.

**Comment by phayes** [comment]
PR is here: https://github.com/RustCrypto/RSA/pull/85 , requires upstream PR to be merged first.

**Comment by tarcieri** [comment]
We'll be bumping (most of) the rest of the RustCrypto to use `rand_core` v0.6 later this month / early next month so it's probably a good time to upgrade.

Definitely agree these are really painful upgrades, especially as `rand` is the most used crate in the entire Rust ecosystem, according to the "Most Downloaded" list on https://crates.io/

**Comment by littledivy** [comment]
rand 0.8 was support was added to num-bigint 0.4.0 so #85 is no longer blocked?
