### ISSUE TITLE
How to use publickey decrypt?

### ISSUE THREAD

**Issue by NateLing** [RustCrypto/RSA#86]
there is no decrypt api for publickey.

**Comment by tarcieri** [comment]
The closest thing to a standardized method of RSA public key decryption I'm aware of are "signcryption" techniques like RSA-PSSR (i.e. RSA-PSS w\ Recovery)

Is there a specific construction you have in mind?

**Comment by NateLing** [comment]
The theory is completely correct. However, the IT department of my company requires that the content we transmit over http must be fully encrypted. This is powerless to refute their request, so I hope that the public key decryption function can be added.

**Comment by dignifiedquire** [comment]
I don't think this is something we are going to add any time soon. If there is a specific construction you are looking for, please open a new issue with links to the specification/paper.

**Comment by tarcieri** [comment]
See #231 for discussion of adding PSS-R support
