### ISSUE TITLE
Feature Request: RSA Blind signing

### ISSUE THREAD

**Issue by phayes** [RustCrypto/RSA#9]
Hi there,

I was wondering if you would be interested in implementing RSA blind-signing in this crate?  

Blind-signing is rare enough that it won't be picked up by any of the mainstream cryptography crates (like ring, openssl etc) so it might make sense to include it here.

**Comment by dignifiedquire** [comment]
It already exists :) https://github.com/RustCrypto/RSA/blob/master/src/key.rs#L416

**Comment by phayes** [comment]
Hi there, 

Thanks for the quick reply.   What I mean specifically, is to allow the following workflow:

1. Alice blinds the hash of a message, generating a blinded message and an unblinder.
2. Alice sends the blind message to the signer Bob. Bob the signer does not know what the message is, since it is blind.  But Bob can still sign the blind message.
3. Alice then "unblinds" the signature (using the unblinder) so that the signature now signs the original message, and not the blind-message that was sent to the signer. 

This type of thing is super useful in instances where someone needs to sign a message without knowing the contents of the message.  This is useful in, for example, online voting where we want to sign the vote as coming from a valid voter, but keep the contents of the vote secret. 

I've implemented such a scheme in Go (https://github.com/cryptoballot/rsablind), and would love to have the same things in Rust.

**Comment by dignifiedquire** [comment]
Very interesting, I did not know about this scheme. In general I would say this is something I would be happy to add, but I can't promise that I will have time to implement it soon . 

Is there an RFC or a paper detailing the scheme that can be used as a reference?

**Comment by phayes** [comment]
Hi @dignifiedquire,

I've done a bunch more research into this, and there isn't really a "standard" for doing RSA blind-signing.   RSA-FDH is pretty close, but it has never been formalized into a spec, so I don't think it belongs in this crate.

I'm going to be creating a new crate called "RSA-FDH" that implements a blind-signing scheme, but it will be a scheme specific to that crate, and not part of any standard. 

What we CAN do in this crate however, is break the core blinding and unblinding functions out to make building an RSA blind-signing crate easier.  I've done that in this PR: #10

**Comment by phayes** [comment]
Closing this. 

RSA blind-signing is implemented in the RSA-FDH crate: https://github.com/phayes/rsa-fdh
