### ISSUE TITLE
Remove std feature requirement for encoding

### ISSUE THREAD

**Issue by AndreVallestero** [RustCrypto/RSA#94]
I would like to use `PrivateKeyPemEncoding` in my Wasm project but RSA currently cannot target Wasm with feature `std` enabled. I am able to compile and generate keys successfully with feature `std` disabled, however I am unable to encode it to a usable format for my use case (pem, pkcs1, jwk).

**Comment by tarcieri** [comment]
The `pkcs8` crate is designed to provide `no_std`-friendly support for PKCS#8 and also supports PEM:

https://github.com/RustCrypto/utils/tree/master/pkcs8

We also own the `pkcs1` crate name. It should be pretty easy to define a similar/compatible `no_std` PKCS#1 encoder (using the [`der` crate](https://github.com/RustCrypto/utils/tree/master/der)).

**Comment by tarcieri** [comment]
I think it's a desired goal for the project, but possibly a dup of #75

**Comment by dignifiedquire** [comment]
fixed on `master`
